name: Deployment

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

env:
  PROFILE: Files
  ENVIRONMENT: PROD

jobs:
  updateTimestamp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: timestampe update
        run: |
          CURRENT_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%S.%N%:z")
          sed -i 's/%CREATED_TIMESTAMP%/'"$CURRENT_TIMESTAMP"'/' .pbixproj.json
      - name: commit and push
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .pbixproj.json
          git commit -am "Update created timestamp"
          git push https://github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
  Deployment:
    runs-on: ubuntu-latest
    environment: PROD
    container:
      image: ghcr.io/pbi-tools/pbi-tools-core:latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: pbi-tools deploy
        run: /app/pbi-tools/pbi-tools.core deploy . "$PROFILE" "$ENVIRONMENT"
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
